package car.auction.datasource;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import car.auction.domain.Buyer;

public class BuyerMapper {
	
	private static final String StatementString = "SELECT * from UPDATE APP.buyer";
	
	private static final String updateStatementString =
            "UPDATE APP.buyer " +
                    "  set username = ?, password = ?, firstname = ?, lastname = ?, phoneno = ?" +
                    "  where id = ?";

    private static final String insertStatementString =
            "INSERT INTO APP.buyer(username, password, firstname, lastname, phoneno) VALUES (?, ?, ?, ?, ?)";
	
	public void update(Buyer b) {
        PreparedStatement updateStatement = null;
        
        try {
            updateStatement = DBConnection.prepare(updateStatementString);
            updateStatement.setString(1, b.getUsername());
            updateStatement.setString(2, b.getPassword());
            updateStatement.setString(3, b.getFirstname());
            updateStatement.setString(4, b.getLastname());
            updateStatement.setString(5, b.getPhoneNumber());
            updateStatement.setInt(6, b.getId());

            updateStatement.execute();

        } catch (Exception e) {

        }
    }

    public int insert(Buyer b) {
        ResultSet autoGenerated = null;

        PreparedStatement insertStatement = null;
        try {
            insertStatement = DBConnection.prepare(insertStatementString, insertStatement.RETURN_GENERATED_KEYS);

            insertStatement.setString(1, b.getUsername());
            insertStatement.setString(2, b.getPassword());
            insertStatement.setString(3, b.getFirstname());
            insertStatement.setString(4, b.getLastname());
            insertStatement.setString(5, b.getPhoneNumber());

            insertStatement.executeUpdate();

            autoGenerated = insertStatement.getGeneratedKeys();
            if (autoGenerated.next()) {
                b.setId(autoGenerated.getInt(1));
            }

            Registry.addBuyer(b);
        } catch (SQLException e) {
        }
        return b.getId();

    }
	
	public static Buyer load(ResultSet rs) throws SQLException {
		int idArg = rs.getInt(1);
		String usernameArg = rs.getString(2);
        String passwordArg = rs.getString(3);
        String firstnameArg = rs.getString(4);
        String lastnameArg = rs.getString(5);
        String phonenoArg = rs.getString(6);
        Buyer result = new Buyer(idArg, usernameArg, passwordArg, firstnameArg, lastnameArg, phonenoArg);
        
        return result;
    }
	
	public static List<Buyer> getAllBuyers () {
		List<Buyer> results = null;
		// TODO add fetching data process
		return results;
	}

	
}
